### ISSUE TITLE
WoW (ruRU) client error

### ISSUE THREAD

**Issue by shikulja** [Haaxor1689/vanilla-autologin#1]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/3386359/215728737-c1b188f8-babc-4a95-99f5-6936a825b159.png">

[Link](https://wowruru.github.io/win_instruction.html)

**Comment by Haaxor1689** [comment]
I've made a proper vanilla version and moved the TurtleWoW version to separate patch. Can you try now please?
