### ISSUE TITLE
Cannot Run, "Login Interface Files Are Corrupt" Error

### ISSUE THREAD

**Issue by JoLiKMC** [Haaxor1689/vanilla-autologin#3]
## What is the issue?
Attempting to use this modification with a **base / stock installation of v1.12.1** doesn't work – it returns the following error:
- "Your login interface files are corrupt. Please reinstall the game."

## What version of *World of Warcraft* are you using?
- **Game Language:** English, United States (enUS)
- **Game Version:** 1.12.1 (5875), Sep. 19 2006
<sup>(installed as v1.12.0 from disc, upgraded to v1.12.1 via first-party patch)</sup>

### Steps to replicate
1. Obtain a **Vanilla** enUS *World of Warcraft* game client.  Upgrade it to v1.12.1 if it isn't already.
2. Place "Patch-Y.mpq" into the `World of Warcraft\Data` folder.
3. Run the game client.

### Expected results
The login interface should have an additional box on the side with account usernames.

### Actual results
The game closes with the error mentioned above.

## Anything else?
The [version](https://github.com/Haaxor1689/turtle-autologin) for *Turtle WoW* works marvelously!  Neither that version *nor* this version seem to want to work with my hand-installed, unmodified v1.12.1 game client, though…  I wish I knew why.  The game works perfectly, as far as I can tell, so I don't *think* anything's missing…  The `readme` didn't mention anything about needing some external modules or anything.  I dunno…

**Comment by Haaxor1689** [comment]
You need to have patched WoW.exe that allows glues patches.

**Comment by JoLiKMC** [comment]
Huh.  That seems like it should've been mentioned in the readme…

Well then, I guess this one was "user error".  My apologies.  Cheers!

**Comment by Haaxor1689** [comment]
I'll add it into the readme :)
